services:
  app:
    build: .
    image: equipment-room-app
    ports:
      - "9002:9002"
    volumes:
      - ./inventory.csv:/app/inventory.csv  # Testing data
      - ./team-members.csv:/app/team-members.csv  # Testing data

